module.exports={
    managerbtn : '/html/body/div/div/div[2]/div/div[1]/div[2]/button',
    customerbtn : '/html/body/div/div/div[2]/div/div[1]/div[1]/button',
    addnewcustomerbtn:'/html/body/div/div/div[2]/div/div[1]/button[1]',
    opennewaccountbtn:'/html/body/div/div/div[2]/div/div[1]/button[2]',
    firstname:'/html/body/div/div/div[2]/div/div[2]/div/div/form/div[1]/input',
    lastname:'/html/body/div/div/div[2]/div/div[2]/div/div/form/div[2]/input',
    postcode:'/html/body/div/div/div[2]/div/div[2]/div/div/form/div[3]/input',
    submitcustomerbtn:'/html/body/div/div/div[2]/div/div[2]/div/div/form/button',
    selectcustomer: '//*[@id="userSelect"]',
    selectcurrency: '//*[@id="currency"]', 
    processbtn:'/html/body/div/div/div[2]/div/div[2]/div/div/form/button',
    loginbtn:'/html/body/div/div/div[2]/div/form/button',
    accnolabel:'/html/body/div/div/div[2]/div/div[2]/strong[1]',
    transactionsbtn: '/html/body/div/div/div[2]/div/div[3]/button[1]',
    depositbtn: '/html/body/div/div/div[2]/div/div[3]/button[2]',
    depositamount: '/html/body/div/div/div[2]/div/div[4]/div/form/div/input',
    submitdepositbtn:'/html/body/div/div/div[2]/div/div[4]/div/form/button',
    withdrawamount: '/html/body/div/div/div[2]/div/div[4]/div/form/div/input',
    submitwithdraw:'/html/body/div/div/div[2]/div/div[4]/div/form/button',
    withdrawbtn:'/html/body/div/div/div[2]/div/div[3]/button[3]',
    customersbtn: '/html/body/div/div/div[2]/div/div[1]/button[3]',
    searchcustomer: '/html/body/div/div/div[2]/div/div[2]/div/form/div/div/input',
    deletebtn: '/html/body/div/div/div[2]/div/div[2]/div/div/table/tbody/tr/td[5]/button'

}